### ISSUE TITLE
First code review and some feedback

### ISSUE THREAD

**Issue by sbz** [dabcoder/countries-cli#1]
After walking through the current `master` code, you will find my feedback below as TODO entries:

- [x] it will be better to declare`baseURL` const outside **main()** function, usually after the imports
- [x] You could use [fmt.Sprintf() function](https://golang.org/pkg/fmt/#Sprintf) to avoid string concatenation using `+` or even [strings.Builder](https://golang.org/pkg/strings/#Builder) introduced in Go `1.10` [version](https://golang.org/doc/go1.10).

- [x] Need to close the body after [http.Response](https://golang.org/pkg/net/http/#Response) creation
After opening the connection using *http.Get()*, you forgot to close the `resp.Body` after the line [42](https://github.com/dabcoder/countries-cli/blob/dc230be27319e3cc43f5afd2fb8955ff5d5234bb/countries.go#L42), you can do it with the following statement: Read more on [defer](https://gobyexample.com/defer)

```golang
defer resp.Body.Close()
```

**Comment by dabcoder** [comment]
Addressed in https://github.com/dabcoder/countries-cli/pull/2
